### PR TITLE
build with Scala 2.12

### PR DESCRIPTION
**Pull request by barkhorn**
This passes all tests, but has some deprecation warnings against Scalatest 3.0
I upgraded to specs2-core 3.8.6 as that is built for Scala 2.12

### CODE REVIEW

**Comment by fommil** [comment]
You're a hero

**Comment by denisrosca** [comment]
Any chance to get this merged and published?

**Comment by barkhorn** [comment]
until this is merged, people can find an interim build (3.3.0-pm) here: https://bintray.com/barkhorn/maven 

With sbt:

libraryDependencies += "org.scalamock" %% "scalamock-core" % "3.3.0-pm" % Test
resolvers += Some(Resolver.bintrayRepo("barkhorn", "maven"))

**Comment by fommil** [comment]
would anyone be interested in taking over maintenance of scalamock? Making regular releases, etc? I'm sure @paulbutcher would be open to the idea

**Comment by barkhorn** [comment]
I don't use Specs2 myself, only Scalatest, but i would be happy to drive this project forward, or collaborate on the maintenance of Scalamock, if Paul wants the help?

**Comment by denisrosca** [comment]
@barkhorn I tried using your workaround from gradle and failed. :| 
Gradle seems to be looking for a SHA1 checksum which seems to be missing.
Would it be too much of hassle to re-publish the artifact with that?

**Comment by barkhorn** [comment]
Hi @denisrosca , I just tried myself with a simple gradle project and didn't get any problems with checksums.
That said, i am struggling to publish sha1 files to bintray using the bintray-sbt plugin. Not sure why these don't appear :-/

build.gradle for Gradle 3.1
```
plugins {
    id "com.github.maiflai.scalatest" version "0.14"
}

apply plugin: 'scala'
apply plugin: 'com.github.maiflai.scalatest'

repositories {
    jcenter()
	maven { url "https://dl.bintray.com/barkhorn/maven" }
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
    compile "org.scala-lang:scala-library:2.12.0"

    testRuntime 'org.pegdown:pegdown:1.6.0'
    testCompile "org.scalatest:scalatest_2.12:3.0.0"
    testCompile "org.scalamock:scalamock-scalatest-support_2.12:3.3.0-pm"
    testCompile "org.scalacheck:scalacheck_2.12:1.13.4"
}
```

**Comment by denisrosca** [comment]
@barkhorn You are right, I've managed to mess up my build somehow. After cleaning/fixing it up a bit it is working ok. Thank you.

**Comment by chipsenkbeil** [comment]
@paulbutcher, have you seen that @barkhorn is willing to drive this project forward? Furthermore, this enables 2.12 support, which is a request many of us have. Do you have some time to check this out?

**Comment by paulbutcher** [comment]
@barkhorn apologies for taking so long to get back to you about this. I'd be happy to hand ScalaMock maintenance over to you.

Giving you access to the GitHub repo is easy enough. What I'm struggling to work out is what I would need to do to allow you to make releases on oss.sonatype.org - I remember that setting it up was a major PITA, and I don't have time to work it all out again. If you know what I need to do and can enlighten me, I'd be very grateful.

Drop me an e-mail ad paul@paulbutcher.com and we can coordinate.

**Comment by fommil** [comment]
I think you can just request perms and point them at this thread.

**Comment by barkhorn** [comment]
Good idea @fommil , I've raised a Jira Task for Sonatype Support.

**Pull request merged**
