### PR TITLE
Scala.js support for ScalaTest 3.0.0

### PR DESCRIPTION
**Pull request by maqdev**
Hi!
This is an implementation targeting support Scala.js 0.6.12. I believe that supporting Scala.js will improve ScalaMock, considering the fact that ScalaTest 3.0.0 now supports Scala.js. At this point, I don't know any other mock library for Scala.js

I've created build.sbt file instead of existing Build.scala and split projects to JS/JVM with moving specific code to appropriate directories. It seems that shell prompt functionality is broken here. It would be great if someone could elaborate more on this.

Things that aren't supported when building for Scala.js are:
- `org.scalamock.scalatest.proxy.MockFactory` support, due to reflection;
- Java specific tests;

There are problems with ScalaTest's traits `OneInstancePerTest`, `RandomTestOrder`. It's required to override method `newInstance` which I did for all tests in ScalaMock.
Also I would like to mention that this pull-request includes https://github.com/paulbutcher/ScalaMock/pull/149 , kudos to @dvic

### CODE REVIEW

**Comment by xavier-fernandez** [comment]
+1

**Comment by cheeseng** [comment]
@maqdev This now seems to have conflicts, do you mind rebase it on the latest master?  Thanks.

**Comment by maqdev** [comment]
@cheeseng done. If you didn't notice I've previously updated this pull-request to cross-compile with scala 2.10 so there will be no need for a separate branch.

If you'll merge this I have a branch with reworked requests #56 and #144, so I could update working code without conflicts for these two requests as well.

It's good to see some life here :)

**Comment by cheeseng** [comment]
@maqdev Thanks, I'll take a look and see if I can merge them in today.

**Comment by chipsenkbeil** [comment]
@cheeseng, any reason this hasn't been merged in? Too much time needed to look over all of the changes?

**Comment by maqdev** [comment]
Conflicts resolved again and updated to latest ScalaJS: 0.6.14. 

ScalaJS now requires NodeJS to run tests, if you want to avoid NodeJS installation you have to use `scalaJSUseRhino in Global := true`

**Comment by barkhorn** [comment]
Hi, this is a pretty big change, with a few structural changes. It'll take a while to review it.
Would be really helpful to know from a high level why files were renamed/moved.
Also, I'm a little confused about node.js - is this only required for the scala.js builds, or for the whole project, after the merge? What is the benefit?

**Comment by sjrd** [comment]
File moves: in a cross-project Scala/JVM + Scala.js, a lot of code can typically be shared between the two platforms. For most projects, virtually all of it can be shared, in fact. This one of the major selling points of Scala.js. However, sometimes, and in particular for "low-level" projects (e.g., a testing framework, or a mocking framework), you sometimes need platform-specific code. This why source files are categories under `shared/`, `jvm/` and `js/`. Hence, a lot of source files typically move from `src/...` to `shared/src/...` when porting a project into a cross-project.

Node.js is the software used to run Scala.js code. Just like you need a JRE to run .class files, you need Node.js to run the .js files produced by Scala.js. This is only required to run/test Scala.js projects, obviously. It is not necessary to run/test Scala/JVM projects. Talking about "benefit" does not really make sense: without it you plain cannot test the Scala.js projects (the Rhino alternative is deprecated and will be removed in Scala.js 1.0.0; it had several severe issues, the least being extremely slow (orders of magnitude) compared to Node.js).

**Comment by maqdev** [comment]
Hi,
on the high level, files where moved to achieve Scalia.js cross build. Files that have common code targeting both JS and JVM targets are moved into 'shared'. And JVM/JS specific files are moved into jvm/js folders correspondingly. You can read more about cross build structure here https://www.scala-js.org/doc/project/cross-build.html

Node.js is required only to run tests targeting JS platform. If you just run `sbt compile`, everything should work out of the box. If you run `sbt test` without nodejs, the tests targeting JS will fail.

**Comment by barkhorn** [comment]
great, thanks.
By using Rhino, can we still run the JS tests successfully?
I think that would be preferrable, to keep the setup simpler for people who want to contribute to this project.

**Comment by xavier-fernandez** [comment]
@barkhorn Now Node.js is the default test runner for ScalaJS: https://www.scala-js.org/news/2016/10/17/announcing-scalajs-0.6.13/

**Comment by sjrd** [comment]
> By using Rhino, can we still run the JS tests successfully?

With Scala.js 0.6.x, yes. Rhino won't be supported by Scala.js 1.0.0, however.

If you are concerned about a simpler setup, I suggest recommending in the Readme that people only run the JVM tests while they develop on their machines. The CI will catch JS-specific errors (which should be rare in practice). Only if one stumbles on a JS-specific error does one need to install Node.js to locally debug it.

**Comment by barkhorn** [comment]
I will add the directive to use Rhino for now, until the documentation is updated to state something similar to @sjrd's comment.

**Comment by barkhorn** [comment]
hi @maqdev @sjrd , version 3.5.0 has been published now.
Grateful if you could test this with some scala.js stuff and see how it hold up.

**Comment by maqdev** [comment]
Thanks @barkhorn! I'll check that

**Comment by maqdev** [comment]
@barkhorn so far this is working fine for me, my library is compiling/testing fine under Scala 2.10-2.12 along with JS. Thank you!

**Comment by barkhorn** [comment]
great news @maqdev . curious which library that is - is it on github?

**Comment by maqdev** [comment]
Sure, it's Json serialization library for Scala/Scala.JS 
https://github.com/hypertino/json-binders

**Comment by maqdev** [comment]
Actually, ScalaMock isn't used in `json-binders` itself, it is used in `binders` https://github.com/hypertino/binders here  :-)

**Pull request merged**
