### PR TITLE
Cross build to scala 3.0.1

### LINKED ISSUE #429: Scala 3 Support
I am looking to upgrade to Scala 3 and I don't see any releases for that yet at https://repo1.maven.org/maven2/org/scalamock/ is that on the near term roadmap?

_Originally posted by @simbo1905 in https://github.com/paulbutcher/ScalaMock/issues/423#issuecomment-1003968026_

### PR DESCRIPTION
**Pull request by custommonkey**
# Pull Request Checklist

* [ ] I agree to licence my contributions under the [MIT licence](https://github.com/paulbutcher/ScalaMock/blob/master/LICENCE)
* [ ] I have added copyright headers to new files
* [ ] I have added tests for any changed functionality

## Fixes

Fixes #429

## Purpose

Support for scala 3

## Background Context

Why did you take this approach?

## References

Are there any relevant issues / PRs / mailing lists discussions?

### CODE REVIEW

**Comment by barkhorn** [comment]
appreciate the help with this, i've approved the workflows so hopefully they will now run on push to this PR

**Comment by barkhorn** [comment]
note that the `.github/workflows/scala.yml` file needs a section for scala 3 as well so it runs a build job for that version

**Comment by mkurz** [comment]
Any news here?

**Comment by barkhorn** [comment]
inactive for over a year, closing this PR

**Pull request closed without merging**
