### PR TITLE
documentation for #234

### LINKED ISSUE #234: Add ability to capture arguments
As far as I can tell ScalaMock lacks the ability to capture arguments a la Mockito's `ArgumentCaptor`. [This StackOverflow post](https://stackoverflow.com/questions/12368938/can-you-capture-and-inspect-arguments-supplied-to-a-method-under-test-with-scala) alludes to a mechanism that exists under-the-hood. It'd be great to expose it, or if it doesn't actually exist, add it. I imagine this can be implemented as a custom matcher.

### PR DESCRIPTION
**Pull request by barkhorn**
# Pull Request Checklist

* [x] I agree to licence my contributions under the [MIT licence](https://github.com/paulbutcher/ScalaMock/blob/master/LICENCE)
* [x] I have added copyright headers to new files
* [x] I have added tests for any changed functionality

## Fixes

Fixes #234

### CODE REVIEW

**Comment by barkhorn** [comment]
merge after #241

**Comment by alexcole** [comment]
@barkhorn - Any chance this will make its way into a release soon? Argument matching seems super useful.

**Comment by barkhorn** [comment]
sure, let me look at doing a release this weekend or next with this change in it.

**Comment by alexcole** [comment]
Woo! Thank you so much! That would be lovely!

**Comment by barkhorn** [comment]
just tried to publish to sonatype but the jar files end up empty. some problem with the sbt build i think :/

**Comment by barkhorn** [comment]
seems to be the scala.js crossbuild. 4.2.0 is now making it's way through the sonatype pipe and should be on maven central soon

**Pull request merged**
